spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/tenant
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        ejb:
          interceptor: id.dias.tenant.TenantInterceptor
server:
  port: 6969